// Original, notification-length summaries of teachings in the Pali Canon.
// These are not verbatim translations. Canonical references are included so
// each summary is traceable without copying a translator's protected wording.
export const BUDDHA_TEACHINGS = {
  english: [
    // Sila and conduct
    'Protect life; do not intentionally kill living beings. — AN 8.54',
    'Take only what is freely given. — AN 8.54',
    'Be faithful and responsible in intimate relationships. — AN 8.54',
    'Let truthfulness be the foundation of your speech. — AN 8.54',
    'Avoid intoxicants that weaken mindfulness and good judgment. — AN 8.54',
    'Do not earn through weapons, trafficking, slaughter, intoxicants, or poison. — AN 5.177',
    'Avoid evil, cultivate what is good, and purify the mind. — Dhammapada 183',
    'Meet hardship with patient endurance rather than harming another. — Dhammapada 184',
    'Do not speak maliciously or cause harm. — Dhammapada 185',
    'Conscience and prudent concern protect a good life. — AN 7.5',
    'Walk the path of right view, intention, speech, action, livelihood, effort, mindfulness, and immersion. — SN 38.3',
    'Practice for restraint and letting go, not possessions, praise, or popularity. — AN 4.25',

    // Wise speech
    'Before speaking, ask: Is it true, beneficial, and the right time? — MN 58',
    'Do not say what is false or pointless, even when people want to hear it. — MN 58',
    'Even an unwelcome truth should be spoken only when it can help. — MN 58',
    'Use kind words, act for others’ welfare, and deal honestly. — DN 31',
    'Let the mind, speech, and actions become calm together. — Dhammapada 96',
    'Guard your speech as carefully as you guard your actions. — Dhammapada 361',
    'Even when provoked, train not to answer with hateful words. — MN 21',
    'Meet lies with truth and anger with non-anger. — Dhammapada 223',

    // Family, friendship, and community
    'Support the parents who supported you. — DN 31',
    'Listen well to teachers and learn your work carefully. — DN 31',
    'Honor your partner with respect, faithfulness, and shared responsibility. — DN 31',
    'Care for your family without neglecting their welfare. — DN 31',
    'Sustain friendship through generosity, kind speech, fairness, and honesty. — DN 31',
    'A true friend protects you when you are vulnerable. — DN 31',
    'A true friend does not abandon you in trouble. — DN 31',
    'A wise friend discourages harm and supports what is good. — DN 31',
    'A compassionate friend does not enjoy your misfortune and rejoices in your success. — DN 31',
    'Give people suitable work, fair wages, care in sickness, and time to rest. — DN 31',
    'Good friendship supports the whole path of practice. — SN 45.2',
    'A strong partnership grows through shared ethics, generosity, and wisdom. — AN 4.55',

    // Work, money, and generosity
    'Work diligently and learn the skills needed to do your work well. — AN 8.54',
    'Protect wealth earned honestly through your own effort. — AN 8.54',
    'Know your income and expenses; keep them in balance. — AN 8.54',
    'Live neither extravagantly nor miserably. — AN 8.54',
    'Gambling, intoxication, heedlessness, and harmful friends drain wealth. — DN 31',
    'Use wealth for living, productive work, and protection against hard times. — DN 31',
    'Give freely; do not let stinginess close the heart. — AN 8.54',
    'A wise person living at home works for the welfare of many. — AN 8.38',
    'Share fairly with those whose work supports your life. — DN 31',
    'Contentment is a form of wealth that cannot be taken away. — Dhammapada 204',

    // Mindfulness, balance, and wisdom
    'Remember regularly: I am subject to aging. — AN 5.57',
    'Remember regularly: I am subject to sickness. — AN 5.57',
    'Remember regularly: I am subject to death. — AN 5.57',
    'Everything dear to me will change and be separated from me. — AN 5.57',
    'My choices are mine; I inherit the results of what I do. — AN 5.57',
    'Pain is one arrow; resistance and despair can become the second. — SN 36.6',
    'The body may be afflicted without the mind being afflicted. — SN 22.1',
    'Gain and loss, praise and blame, pleasure and pain all change. — AN 8.6',
    'Like a solid rock in wind, do not be ruled by praise or blame. — Dhammapada 81',
    'When pleasure or pain arrives, notice it without becoming elated or defeated. — Dhammapada 83',
    'Train the mind like the earth: receive pleasant and unpleasant contact without being overpowered. — MN 62',
    'Cultivate equanimity to weaken aversion. — MN 62',
    'See that all conditioned experiences are impermanent. — Dhammapada 277',
    'See that clinging to conditioned experiences cannot provide lasting satisfaction. — Dhammapada 278',
    'See that no experience can rightly be held as a permanent self. — Dhammapada 279',
    'Observe body, feelings, mind, and principles with diligence and clear awareness. — SN 47.1',
    'May every being be happy and safe. — Sutta Nipata 1.8',
    'Do not deceive, despise, or wish suffering on another. — Sutta Nipata 1.8',
  ],
  hindi: [
    // शील और आचरण
    'जीवन की रक्षा करें; जानबूझकर किसी प्राणी की हत्या न करें। — अंगुत्तर निकाय 8.54',
    'केवल वही लें जो स्वेच्छा से दिया गया हो। — अंगुत्तर निकाय 8.54',
    'घनिष्ठ संबंधों में निष्ठावान और जिम्मेदार रहें। — अंगुत्तर निकाय 8.54',
    'सत्य को अपनी वाणी का आधार बनाएँ। — अंगुत्तर निकाय 8.54',
    'सजगता और विवेक को कमजोर करने वाले नशे से बचें। — अंगुत्तर निकाय 8.54',
    'हथियार, मानव-व्यापार, वध, नशे या विष से जीविका न चलाएँ। — अंगुत्तर निकाय 5.177',
    'बुराई से बचें, अच्छाई बढ़ाएँ और मन को शुद्ध करें। — धम्मपद 183',
    'कठिनाई में किसी को हानि पहुँचाने के बजाय धैर्य रखें। — धम्मपद 184',
    'दुर्भावना से न बोलें और किसी को हानि न पहुँचाएँ। — धम्मपद 185',
    'लज्जा और अपाय का विवेक अच्छे जीवन की रक्षा करते हैं। — अंगुत्तर निकाय 7.5',
    'सम्यक दृष्टि, संकल्प, वाणी, कर्म, आजीविका, प्रयास, स्मृति और समाधि के मार्ग पर चलें। — संयुत्त निकाय 38.3',
    'संपत्ति, प्रशंसा या प्रसिद्धि के लिए नहीं; संयम और त्याग के लिए साधना करें। — अंगुत्तर निकाय 4.25',

    // सम्यक वाणी
    'बोलने से पहले पूछें: क्या यह सत्य, हितकारी और सही समय पर है? — मज्झिम निकाय 58',
    'झूठी या निरर्थक बात न कहें, भले ही लोग उसे सुनना चाहें। — मज्झिम निकाय 58',
    'अप्रिय सत्य भी तभी कहें जब वह सच में सहायता कर सके। — मज्झिम निकाय 58',
    'मधुर वाणी बोलें, दूसरों का हित करें और ईमानदारी से व्यवहार करें। — दीघ निकाय 31',
    'मन, वाणी और कर्म—तीनों को साथ शांत होने दें। — धम्मपद 96',
    'वाणी की रक्षा उतनी ही सावधानी से करें जितनी अपने कर्मों की। — धम्मपद 361',
    'उकसाए जाने पर भी द्वेषपूर्ण उत्तर न देने का अभ्यास करें। — मज्झिम निकाय 21',
    'झूठ को सत्य से और क्रोध को अक्रोध से जीतें। — धम्मपद 223',

    // परिवार, मित्रता और समाज
    'जिन माता-पिता ने आपका सहारा दिया, उनका सहारा बनें। — दीघ निकाय 31',
    'गुरुओं की बात ध्यान से सुनें और अपना काम अच्छी तरह सीखें। — दीघ निकाय 31',
    'अपने साथी का सम्मान, निष्ठा और साझा जिम्मेदारी से आदर करें। — दीघ निकाय 31',
    'परिवार की देखभाल करें और उसके कल्याण की उपेक्षा न करें। — दीघ निकाय 31',
    'दान, मधुर वाणी, निष्पक्षता और ईमानदारी से मित्रता निभाएँ। — दीघ निकाय 31',
    'सच्चा मित्र आपकी असावधानी और संकट में रक्षा करता है। — दीघ निकाय 31',
    'सच्चा मित्र कठिन समय में आपको नहीं छोड़ता। — दीघ निकाय 31',
    'बुद्धिमान मित्र बुराई से रोकता और अच्छाई में सहारा देता है। — दीघ निकाय 31',
    'करुणामय मित्र आपके दुख में प्रसन्न नहीं होता और सफलता में आनंदित होता है। — दीघ निकाय 31',
    'योग्यता के अनुसार काम, उचित वेतन, बीमारी में देखभाल और विश्राम दें। — दीघ निकाय 31',
    'कल्याण-मित्रता पूरे साधना-मार्ग को सहारा देती है। — संयुत्त निकाय 45.2',
    'साझा शील, उदारता और प्रज्ञा से संबंध मजबूत होता है। — अंगुत्तर निकाय 4.55',

    // काम, धन और उदारता
    'मेहनत से काम करें और उसे अच्छी तरह करने का कौशल सीखें। — अंगुत्तर निकाय 8.54',
    'ईमानदार प्रयास से कमाए धन की सावधानी से रक्षा करें। — अंगुत्तर निकाय 8.54',
    'अपनी आय और व्यय जानें तथा उन्हें संतुलित रखें। — अंगुत्तर निकाय 8.54',
    'न फिजूलखर्च बनें, न अपने साथ कृपणता करें। — अंगुत्तर निकाय 8.54',
    'जुआ, नशा, लापरवाही और बुरी संगति धन को नष्ट करते हैं। — दीघ निकाय 31',
    'धन का उपयोग जीवन, उपयोगी काम और कठिन समय की सुरक्षा के लिए करें। — दीघ निकाय 31',
    'खुले हाथ से दें; कृपणता को हृदय बंद न करने दें। — अंगुत्तर निकाय 8.54',
    'बुद्धिमान गृहस्थ अनेक लोगों के कल्याण के लिए काम करता है। — अंगुत्तर निकाय 8.38',
    'जिनके श्रम से आपका जीवन चलता है, उनके साथ न्यायपूर्वक बाँटें। — दीघ निकाय 31',
    'संतोष ऐसा धन है जिसे कोई छीन नहीं सकता। — धम्मपद 204',

    // सजगता, समता और प्रज्ञा
    'नियमित स्मरण करें: मैं वृद्ध होने के स्वभाव वाला हूँ। — अंगुत्तर निकाय 5.57',
    'नियमित स्मरण करें: मैं रोगी होने के स्वभाव वाला हूँ। — अंगुत्तर निकाय 5.57',
    'नियमित स्मरण करें: मैं मृत्यु से मुक्त नहीं हूँ। — अंगुत्तर निकाय 5.57',
    'मेरी हर प्रिय वस्तु बदलेगी और मुझसे अलग होगी। — अंगुत्तर निकाय 5.57',
    'मेरे कर्म मेरे हैं; मैं अपने चुनावों का फल पाऊँगा। — अंगुत्तर निकाय 5.57',
    'पीड़ा पहला तीर है; विरोध और निराशा दूसरा तीर बन सकते हैं। — संयुत्त निकाय 36.6',
    'शरीर पीड़ित हो सकता है, पर मन को पीड़ित होना जरूरी नहीं। — संयुत्त निकाय 22.1',
    'लाभ-हानि, निंदा-प्रशंसा और सुख-दुख सभी बदलते हैं। — अंगुत्तर निकाय 8.6',
    'हवा में अडिग चट्टान की तरह निंदा-प्रशंसा से संचालित न हों। — धम्मपद 81',
    'सुख या पीड़ा आए तो उसे देखें; न उछलें, न टूटें। — धम्मपद 83',
    'मन को पृथ्वी जैसा बनाएँ: सुखद-असुखद स्पर्श से अभिभूत न हों। — मज्झिम निकाय 62',
    'द्वेष को कमजोर करने के लिए समता विकसित करें। — मज्झिम निकाय 62',
    'सभी संस्कारित अनुभवों की अनित्यता देखें। — धम्मपद 277',
    'संस्कारित अनुभवों से चिपकना स्थायी संतोष नहीं दे सकता। — धम्मपद 278',
    'किसी अनुभव को स्थायी आत्मा नहीं माना जा सकता। — धम्मपद 279',
    'शरीर, संवेदना, मन और धम्म को परिश्रम तथा स्पष्ट सजगता से देखें। — संयुत्त निकाय 47.1',
    'सभी प्राणी सुखी और सुरक्षित हों। — सुत्तनिपात 1.8',
    'किसी को धोखा न दें, नीचा न समझें और उसके दुख की कामना न करें। — सुत्तनिपात 1.8',
  ],
};
